### ISSUE TITLE
Keep both biblatex and csl workflows?

### ISSUE THREAD

**Issue by webbedfeet** [mitchelloharawild/vitae#118]
Hello Mitchell,

I know that in 0.2.1 you switched over from a biblatex workflow to a citeproc/csl workflow to take advantage of pandoc's capabilities. Is it possible to have both functionalities in some sense. I have some macros to modify my references through the biblatex workflow that obviously don't work now. I wonder if there can be a choice of which route to go, since the csl route certainly is powerful and effective for full documents. 

My particular use cases are typesetting my name in bold in the publications bibliography of my CV, and adding on PMID (PubMed identifiers) that are often required in the US in biomedical research for grant applications, reviews and the like. There's only one published CSL available with this, from National Library of Medicine in the US, but I'm not overjoyed with that choice.

**Comment by mitchelloharawild** [comment]
Thanks for your feedback. It would be possible to retain legacy functionality via a `legacy` or `bibtex` argument, however if possible the creation of CSL files is encouraged. This is because the biblatex workflow is only appropriate for PDF outputs, and I have plans for including HTML/word CV templates (#8, #24).

CSL styles which include pubmed can be found with this search: https://github.com/citation-style-language/styles/search?q=PMID&unscoped_q=PMID
You can also modify a preferred style to support pubmed by copying the relevant PMID code into an existing style.

As for bolding your name, I'm not sure if this can be done with CSL. How are you doing it currently with biblatex?

**Comment by webbedfeet** [comment]
I have a biblatex macro that bolds the names. I like CSL in general,  but my workflow depended on biblatex. I appreciate moving to Word/HTML formats (that is great), and so I do like the direction. 

I've basically forked your repo and created a biblatex branch from v0.2.0. If I install from that branch, I'm fine. When I'll want csl, I can just move to the master branch (actually created a csl branch which is up to date with master) and re-install the package from there. It's not onerous right now, but a programmatic switch might allow us legacy users from having to move pipelines.

Love what you've done with this. I adopted Rob Hyndman's CV in LaTeX many years ago, and being able to do all of this in R is fantastic thanks to your efforts.

**Comment by mitchelloharawild** [comment]
You may be interested in a lua filter for bolding names: https://github.com/jooyoungseo/jy_CV/blob/master/lua/strong.lua

**Comment by mitchelloharawild** [comment]
Closing as maintaining multiple implementations for bibliographies over-complicates the package, and it is possible to use lua filters to apply non-standard formatting to bibliographies.
