### ISSUE TITLE
Allow CSL JSON for bibliography_entries

### ISSUE THREAD

**Issue by adam3smith** [mitchelloharawild/vitae#164]
---

Brief description of the problem:
It'd be very nice if we could provide the metadata for bibliographies in CSL JSON directly (e.g. Zotero exports that, as do CrossRef and DataCite). Because it avoids the conversion from bibtex to json that pandoc_citeproc does internally, it tends to produce better output. Currently trying to use a json file (unsurprisingly) fails as per the below.

```{r}
library(dplyr)


bibliography_entries("peer-reviewed.json") %>%
  arrange(desc(issued))
```

Fails with

```
Error in rmarkdown::pandoc_citeproc_convert(file) : 
  Error 1 occurred building shared library.
Calls: <Anonymous> ... %>% -> arrange -> bibliography_entries -> <Anonymous>
In addition: Warning message:
In system(command, intern = TRUE) :
  running command '"C:/PROGRA~1/Pandoc/pandoc-citeproc.exe" --bib2json peer-reviewed.json' had status 1
```

**Comment by mitchelloharawild** [comment]
I think you understand the problem here better than I do. Is this something that can typically be used directly in pandoc?

Internally, `bibliography_entries()` essentially uses `pandoc_citeproc_convert(file, type = "list")` with some further manipulation to arrange it in a tabular format. Are you suggesting that if a json file (and possibly yaml?) is provided, then some other process is used to convert json/yaml -> R list?

Could you provide a sample of your json for me to work with?

**Comment by mitchelloharawild** [comment]
Closing as I believe that the error you have is unrelated to the type of bibliography you are providing, and a MRE hasn't been provided.
The error suggests that there is an issue accessing / using the pandoc citeproc utility.
