### ISSUE TITLE
Allow alternate CSL for formatting bibliography

### ISSUE THREAD

**Issue by rdocking** [mitchelloharawild/vitae#52]
Hi there - I'm really liking this package for getting my CV up to date. One feature I really like in standard RMarkdown is the ability to specify alternate CSL files for formatting the bibliography:

https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_styles

Would it be possible for vitae to support `csl` in the YAML header, and pass it on to pandoc/latex?

I looked at the `pandoc_args` in:

`cv_document(..., pandoc_args = NULL, pandoc_vars = NULL)`

... but couldn't figure out how to make this work. Thanks!

**Comment by mitchelloharawild** [comment]
It should be possible, and if it's not then I'll add it soon (next release coming up soon, which I'll try to include this in).

**Comment by mitchelloharawild** [comment]
I've looked into this a bit further and I'm less confident that it's possible with CSL.

When specifying a bibliography with pandoc, it is added to the end of the document and formatted using the CSL. When using vitae, we don't always want the bibliography placed at the end, and so pandoc is not used to create the bibliography. As pandoc is not used, I don't know of a nice way to use CSL to format the bibliography.

What I do think is more feasible would be to allow custom bst files to be provided, but I'll need to think about this some more.

**Comment by jobreu** [comment]
I agree that it would be great if it was possible to use alternative CSL (for example, in my field APA style is the usual format). Somewhat related to that, I was wondering whether you have any plans to implement the option to use a descending numbering of publications (as discussed in [#33](https://github.com/ropenscilabs/vitae/issues/33))

**Comment by SarBearSchwartz** [comment]
I am trying to figure out how to use APA style in the publication list, as well.  Any new ideas?

**Comment by RLumSK** [comment]
I encountered similar difficulties and I think an alternative would be to allow the user to provide its own bibliography format file. 

So far everything appears to be hardwired to the `bib_format.tex` (inst/bib_format.tex) file (inserted by `cv_document()`) which seems to be always taken, no matter what kind of template is used. I tried to use `header-includes:` in the YAML header, but the problem is what ever I add here, gets placed before ` bib_format.tex` is included. So, for example, if I want to use 

```tex
\AtEveryBibitem{\clearfield{month}}
\AtEveryBibitem{\clearfield{day}}
```

to remove the months and the day from publication list it does not work, because the fields are not yet known to the processor. I have three suggestions for an enhancement: 

* The function `cv_document()` gains a new argument, e.g., `bib_format` that allows each template to ship its own `bibformat.tex` (if nothing is provided it falls back to the default). 

* `bibformat.tex` is included before I include the headers. However, this may not work for other reasons and it gives less flexibility at hand. 

* The last option would be to allow an own file in the YAML header (so far this is feasible)

For the moment, for me the easiest way was to direclty modify `bib_format.tex` and then rebuild the package. It works nice, but perhaps there are more elegant solutions. 

Last: Thanks to the package authors for their work on the package 'vitae'.

**Comment by achamess** [comment]
Can we revisit this? The publications section is probably the most important part of many academic CVs, and being able to specifically style it is pretty important, I'd say. I want very much to use the `vitae` package but not being able to control the style of the publications section would be a major gap for me.

**Comment by mitchelloharawild** [comment]
I don't think we can support CSL as we are using biblatex to display/format the bibliography entries.
We can expose some control parameters used in the `bib_format.tex` file if needed. I'm not entirely sure which options are required. Perhaps something similar to how `geometry` is handled would be appropriate here.

**Comment by RLumSK** [comment]
Just to pick-up my comment again: What would be the reasons not to allow a custom `bib_format.tex` file via YAML? Of course, it is not so smooth and the hammer solution, however, it would be still easier than modifying the `bib_format.tex` and then rebuild the package. 

I know, people can contribute new styles for 'vitae', but most of your already integrated styles are simply perfect (thanks again for this work!), just the publication section usually needs substantial customisation to fulfil various demands by institutes and funding organisations.

**Comment by achamess** [comment]
Those sound like possible solutions. Can one make fine-grained control via the bib_format.tex file?

**Comment by jooyoungseo** [comment]
I have addressed this issue.

After reading [this Stack Overflow question](https://stackoverflow.com/questions/49707298/how-to-get-a-second-bibliography), I have downloaded [multiple-bibliographies.lua](https://github.com/pandoc/lua-filters/tree/master/multiple-bibliographies) file.

I could commit myself to making the workflow smoother when my time allows through a PR.

**Comment by mitchelloharawild** [comment]
CSL is now supported :tada:
