### ISSUE TITLE
Spacing in detailed_entries() when "why" argument is missing

### ISSUE THREAD

**Issue by lindsayevanslee** [mitchelloharawild/vitae#77]
Hello, I am building a CV with the "awesomeCV" format, using detailed_entries() for the education section, but leaving the "why" argument missing (following exactly the Rmd template for this format). When this argument is missing, there is still a rather large space between the entries, as if it's adding a line break where it is expecting to put bullet points.

Would it be possible to edit this function so that if "why" is missing there is not this large space between entries? 

```r
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Informal studies", "1889-91", "Flying University", "Warsaw, Poland",
  "Master of Physics", "1893", "Sorbonne Université", "Paris, France",
  "Master of Mathematics", "1894", "Sorbonne Université", "Paris, France"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

<img width="754" alt="Screenshot 2019-08-29 11 49 43" src="https://user-images.githubusercontent.com/22692101/63930188-1da59d00-ca53-11e9-8775-58888473d255.png">

**Comment by mitchelloharawild** [comment]
This is the spacing used by the [Awesome-CV](https://github.com/posquit0/Awesome-CV) template. If you make changes to the awesome-cv document class, they will be reflected in the CV output.

**Comment by zhiiiyang** [comment]
However, after altering the class in the awesome-cv.cls, it doesn't reduce the space. 
https://github.com/posquit0/Awesome-CV/issues/249#issuecomment-470629007

```
% Define an entry of cv information
% Usage: \cventry{<position>}{<title>}{<location>}{<date>}{<description>}
\newcommand*{\cventry}[5]{%
  \vspace{-2.0mm}
  \setlength\tabcolsep{0pt}
  \setlength{\extrarowheight}{0pt}
  \begin{tabular*}{\textwidth}{@{\extracolsep{\fill}} L{\textwidth - 4.5cm} R{4.5cm}}
    \ifempty{#2#3}
      {\entrypositionstyle{#1} & \entrydatestyle{#4} \\}
      {\entrytitlestyle{#2} & \entrylocationstyle{#3} \\
      \entrypositionstyle{#1} & \entrydatestyle{#4}}
    \ifempty{#5}{}{\\\multicolumn{2}{L{\textwidth}}{\descriptionstyle{#5}}}
  \end{tabular*}%
}
```

It is because \empty is generated in the last {}, which causes `\ifempty{#5}{}{\\\multicolumn{2}{L{\textwidth}}{\descriptionstyle{#5}}}` to fail.  

```
\detaileditem{degree}
{dates}
{school}
{location}
{\empty}
```

Is it possible that we can change the Latex output to be the following?
```
\detaileditem{degree}
{dates}
{school}
{location}
{}
```

I've tested the above in overleaf and it reduces the space. 
![image](https://user-images.githubusercontent.com/7269113/64918605-6c427f00-d755-11e9-8db3-a1a882ecfc82.png)

**Comment by brooksambrose** [comment]
This is a problem with the underlying template not vitae, but in #89 I proposed a hack to the internal vitae template that exploits the convention that all lines in the base template are 4mm, so `\vspace{-4.0mm}` if why is empty. Since vitae is a wrapper around the base template it seems less confusing to modify the wrapping rather than propose a new template with fixes...?
